version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/reane-backend
  mysql:
    image: mysql:8.3
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: reana
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - app-network
  frontend:
   build:
     context: .
     dockerfile: ./frontend/Dockerfile
   volumes:
     - ./frontend/src:/app
   command: 'npm run dev'
   ports:
     - 3000:3000
   networks:
     - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    ports:
      - 8081:80
    networks:
      - app-network
    platform: linux/amd64  # 追加
networks:
  app-network:
    driver: bridge
volumes:
  mysql-volume: